/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package luongnd.ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import luongnd.dao.ItemDAO;
import luongnd.dao.SupplierDAO;
import luongnd.dto.ItemDTO;
import luongnd.dto.SuppliersDTO;

/**
 *
 * @author Dell
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    private DefaultTableModel tblModelUserSupplier;
    private DefaultTableModel tblModelUserItem;
    boolean addNewSupplier = true;
    boolean addNewItem = true;

    public Main() throws SQLException, Exception {

        initComponents();
        tblModelUserItem = (DefaultTableModel) tblViewItem.getModel();
        tblModelUserSupplier = (DefaultTableModel) tblViewSupplier.getModel();
        displaySupplier();
        displayItem();
        // loadDataItem();
        loadDaTaComBox();
        setLocationRelativeTo(null);
    }

    public void displaySupplier() throws SQLException {

        ArrayList<SuppliersDTO> list = new SupplierDAO().getSupplier();
        tblModelUserSupplier.setRowCount(0);
        for (SuppliersDTO suppliersDTO : list) {
            tblModelUserSupplier.addRow(suppliersDTO.toVector());
        }

    }
//    void loadDataItem() {
//        try {
//            ItemDAO itemDao = new ItemDAO();
//            List<ItemDTO> listItem = itemDao.getAllItems();
//            SupplierDAO supDao = new SupplierDAO();
//            List<SuppliersDTO> listSupplier = supDao.getSupplier();
//            tblModelUserItem.setRowCount(0);
//            for (ItemDTO itemDTO : listItem) {
//                tblModelUserItem.addRow(itemDTO.toVector());
//            }
//            loadDaTaComBox();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }

    public void displayItem() throws SQLException, Exception {
        ArrayList<ItemDTO> list = new ItemDAO().getItem();
        tblModelUserItem.setRowCount(0);
        for (ItemDTO itemDTO : list) {
            tblModelUserItem.addRow(itemDTO.toVector());
        }

    }

    public void loadDaTaComBox() {
 
        try {
            cbSupplier.removeAllItems();
            SupplierDAO dao = new SupplierDAO();
            List<SuppliersDTO> listSupplier = dao.getSupplier();
            for (SuppliersDTO supplierDTO : listSupplier) {
                cbSupplier.addItem(supplierDTO.getSupCode() + "-" + supplierDTO.getSupName());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        JCRoll1 = new javax.swing.JScrollPane();
        tblViewSupplier = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtCodeSupllier = new javax.swing.JTextField();
        txtNameSupllier = new javax.swing.JTextField();
        txtAddressSupllier = new javax.swing.JTextField();
        cbCollaborating = new javax.swing.JCheckBox();
        btnAddNew = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Jcroll2 = new javax.swing.JScrollPane();
        tblViewItem = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtUnit = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        cbSupplying = new javax.swing.JCheckBox();
        btnAddnewItem = new javax.swing.JButton();
        btnSaveItem = new javax.swing.JButton();
        btnDeleteItem = new javax.swing.JButton();
        cbSupplier = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblViewSupplier.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        tblViewSupplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Code", "Name", "Address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblViewSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewSupplierMouseClicked(evt);
            }
        });
        JCRoll1.setViewportView(tblViewSupplier);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Code");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Address");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Collaborating");

        btnAddNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddNew.setText("Add new");
        btnAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNameSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodeSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(55, 55, 55)
                        .addComponent(txtAddressSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(32, 32, 32)
                        .addComponent(cbCollaborating)))
                .addContainerGap(187, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtCodeSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtNameSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(txtAddressSupllier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(cbCollaborating))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(JCRoll1, javax.swing.GroupLayout.PREFERRED_SIZE, 554, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JCRoll1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 60, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Supplier", jPanel1);

        tblViewItem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblViewItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item Code", "Name", "Unit", "Price", "Supplying", "Suppliers"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Byte.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblViewItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewItemMouseClicked(evt);
            }
        });
        Jcroll2.setViewportView(tblViewItem);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Details"));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Item Code");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Unit");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Price");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Supplying");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Supplier");

        txtItemName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemNameActionPerformed(evt);
            }
        });

        btnAddnewItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddnewItem.setText("Add new");
        btnAddnewItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddnewItemActionPerformed(evt);
            }
        });

        btnSaveItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSaveItem.setText("Save");
        btnSaveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveItemActionPerformed(evt);
            }
        });

        btnDeleteItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDeleteItem.setText("Delete");
        btnDeleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteItemActionPerformed(evt);
            }
        });

        cbSupplier.setToolTipText("");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(cbSupplying))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAddnewItem)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveItem, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteItem, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)))
                .addContainerGap(244, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbSupplying)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddnewItem)
                    .addComponent(btnSaveItem)
                    .addComponent(btnDeleteItem))
                .addGap(75, 75, 75))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(Jcroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(Jcroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Item", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Item");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblViewSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewSupplierMouseClicked
        // TODO add your handling code here:
        try {
            //Neu click vao table thì là false để thực hiện cập nhật
            addNewSupplier = false;
            int row = tblViewSupplier.getSelectedRow();
            String id = (String) tblViewSupplier.getValueAt(row, 0);
            SupplierDAO dao = new SupplierDAO();
            SuppliersDTO dto = dao.findbyprimarykey(id);
            txtCodeSupllier.setText(dto.getSupCode());
            txtCodeSupllier.setEditable(false);
            txtNameSupllier.setText(dto.getSupName());
            txtAddressSupllier.setText(dto.getAddress());
            if (dto.isCollaborating()) {
                cbCollaborating.setSelected(true);
            } else {
                cbCollaborating.setSelected(false);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_tblViewSupplierMouseClicked

    private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
        // TODO add your handling code here:
        // Nếu click addNew thì là true để thực hiện thêm mới
        addNewSupplier = true;
        txtCodeSupllier.setText("");
        txtCodeSupllier.setEditable(true);
        txtNameSupllier.setText("");
        txtAddressSupllier.setText("");
        cbCollaborating.setSelected(false);
    }//GEN-LAST:event_btnAddNewActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        int row = tblViewSupplier.getSelectedRow();
        String code = txtCodeSupllier.getText();
        if (code.length() > 10) {
            JOptionPane.showMessageDialog(this, "Smaller than 10 character");
            txtCodeSupllier.setText("");
            return;
        }

        String name = txtNameSupllier.getText();
        String address = txtAddressSupllier.getText();
        boolean collaborating = cbCollaborating.isSelected();
        String valid = "";
        SupplierDAO dao = new SupplierDAO();
        SuppliersDTO dto = new SuppliersDTO(code, name, address, collaborating);
        try {

            if (dao.checkBlank(code)) {
                valid += "Id can not be blank\n";
            }
            if (dao.checkBlank(name)) {
                valid += "Name can not be blank\n";
            }
            if (dao.checkBlank(address)) {
                valid += "Address can not be blank\n";
            }
            if (valid.equals("")) {

                if (addNewSupplier) {
                    ArrayList<SuppliersDTO> list = new SupplierDAO().getSupplier();
                    if (dao.checkDuplicate(list, code)) {
                        JOptionPane.showMessageDialog(this, "Duplicate");
                        return;
                    }
                    if (dao.insert(dto)) {
                        JOptionPane.showMessageDialog(this, "Insert Successful");
                        tblModelUserSupplier.addRow(dto.toVector());
                        cbSupplier.removeAllItems();
                        loadDaTaComBox();
                    }
                } else {
                    if (dao.update(dto)) {
                        JOptionPane.showMessageDialog(this, "Update successful");
                        tblModelUserSupplier.setValueAt(name, row, 1);
                        tblModelUserSupplier.setValueAt(address, row, 2);
                        cbSupplier.removeAllItems();
                        loadDaTaComBox();
                        displayItem();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, valid);
            }

        } catch (Exception e) {
            //  e.printStackTrace();
//            if(e.getMessage().contains("duplicate")){
//                JOptionPane.showMessageDialog(this, "Duplicate");
//        }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        int r = JOptionPane.showConfirmDialog(this, "Are you sure", "remove?", JOptionPane.YES_OPTION);
        if (r == JOptionPane.YES_OPTION) {
            try {
                int selectedRow = tblViewSupplier.getSelectedRow();
                String supCode = tblModelUserSupplier.getValueAt(selectedRow, 0).toString();
                ItemDAO itemDao = new ItemDAO();
                if (itemDao.CheckItems(supCode)) {
                    JOptionPane.showMessageDialog(this, "remove items of this supply first");
                    return;
                }
                SupplierDAO dao = new SupplierDAO();
                if (dao.delete(supCode)) {
                    JOptionPane.showMessageDialog(this, "Delete successful");
                    tblModelUserSupplier.removeRow(selectedRow);
                    btnAddNewActionPerformed(evt);
                    cbSupplier.removeAllItems();
                    loadDaTaComBox();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddnewItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddnewItemActionPerformed
        // TODO add your handling code here:
        addNewItem = true;
        txtItemCode.setText("");
        txtItemCode.setEditable(true);
        txtItemName.setText("");
        txtUnit.setText("");
        txtPrice.setText("");
        cbSupplying.setSelected(false);
        // cbSupplier.setSelectedItem("-Choice-");
    }//GEN-LAST:event_btnAddnewItemActionPerformed

    private void txtItemNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemNameActionPerformed

    private void tblViewItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewItemMouseClicked
        try {
            // TODO add your handling code here:
            addNewItem = false;
            int row = tblViewItem.getSelectedRow();
            String id = (String) tblViewItem.getValueAt(row, 0);
            ItemDAO dao = new ItemDAO();
            ItemDTO dto = dao.findbyprimarykey(id);
            txtItemCode.setText(dto.getItemCode());
            txtItemCode.setEditable(false);
            txtItemName.setText(dto.getItemName());
            txtUnit.setText(dto.getUnit());
            txtPrice.setText(String.valueOf(dto.getPrice()));
            cbSupplier.setSelectedItem(tblViewItem.getValueAt(row, 5).toString());
            if (dto.isSupplying()) {
                cbSupplying.setSelected(true);
            } else {
                cbSupplying.setSelected(false);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_tblViewItemMouseClicked

    private void btnSaveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveItemActionPerformed
        // TODO add your handling code here:

        int row = tblViewItem.getSelectedRow();
        String id = txtItemCode.getText();
        String name = txtItemName.getText();
        String unit = txtUnit.getText();
        String price = txtPrice.getText();
        boolean supplying;
        if (cbSupplying.isSelected()) {
            supplying = true;
        } else {
            supplying = false;
        }
        String supplier = (String) cbSupplier.getSelectedItem();
        float newPrice = 0;

        String valid = "";
        ItemDAO dao = new ItemDAO();

        try {
            if (dao.checkBlank(id)) {
                valid += "Id can not be blank \n";
            }
            if (dao.checkBlank(name)) {
                valid += "Name can not be blank \n";
            }
            if (dao.checkBlank(unit)) {
                valid += "Unit can not be blank \n";
            }
            if (dao.checkBlank(price)) {
                valid += "Price can not be blank \n";
            }
            if (dao.checkPrice(price)) {
                valid += "Price must be bigger than 0";
            }
//            if (price.matches("[\\s]*[0-9]*[1-9]+")) {
//                newPrice = Float.parseFloat(price);
//            } else {
//                valid+="Price is a number\n";
//                //JOptionPane.showMessageDialog(this, "price is a number");
//                
//            }

            if (valid.equals("")) {
                // ItemDAO dao = new ItemDAO();
//                float prices = Float.parseFloat(txtPrice.getText());
//                ItemDTO dto = new ItemDTO(id, name, unit, prices, supplying, supplier);
                SupplierDAO supDao = new SupplierDAO();
                String[] itemSupCode = supplier.split("-", 0);
                ItemDTO dto = new ItemDTO(id, name, unit,Float.parseFloat(price), supplying, itemSupCode[0]);

                if (addNewItem) {
                    ArrayList<ItemDTO> list1 = new ItemDAO().getItem();
                    if (dao.checkDuplicate(list1, id)) {
                        JOptionPane.showMessageDialog(this, "Duplicate");
                        return;
                    }
                    if (dao.insert(dto)) {
                        JOptionPane.showMessageDialog(this, "Insert Successful");
                        tblModelUserItem.addRow(dto.toVector());
                        cbSupplier.removeAllItems();
                        loadDaTaComBox();
                    }
                } else {
                    if (dao.update(dto)) {
                        JOptionPane.showMessageDialog(this, "Update successful");
                        displayItem();
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, valid);
            }
        } catch (Exception e) {
            // e.printStackTrace();
            if (e.getMessage().contains("duplicate")) {
                JOptionPane.showMessageDialog(this, "Dupplicated");
            }
            if(e.getMessage().contains("For input")){
            JOptionPane.showMessageDialog(this, "Error! Pice is a number!!!");
            }

        }

    }//GEN-LAST:event_btnSaveItemActionPerformed

    private void btnDeleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteItemActionPerformed
        // TODO add your handling code here:
        int row = tblViewItem.getSelectedRow();
        try {
            String userIdItem = (String) tblModelUserItem.getValueAt(row, 0);
            ItemDAO dao = new ItemDAO();
            int info = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Thông báo", JOptionPane.YES_OPTION);
            if (info == 0) {
                if (dao.delete(userIdItem)) {
                    JOptionPane.showMessageDialog(this, "Delete Successful");
                    tblModelUserItem.removeRow(row);
                    btnAddnewItemActionPerformed(evt);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnDeleteItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Main().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JCRoll1;
    private javax.swing.JScrollPane Jcroll2;
    private javax.swing.JButton btnAddNew;
    private javax.swing.JButton btnAddnewItem;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnDeleteItem;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSaveItem;
    private javax.swing.JCheckBox cbCollaborating;
    private javax.swing.JComboBox<String> cbSupplier;
    private javax.swing.JCheckBox cbSupplying;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tblViewItem;
    private javax.swing.JTable tblViewSupplier;
    private javax.swing.JTextField txtAddressSupllier;
    private javax.swing.JTextField txtCodeSupllier;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtNameSupllier;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtUnit;
    // End of variables declaration//GEN-END:variables
}
